experiment:
  name: "electra_base_experiment"
  description: "ELECTRA Base model for sentiment analysis"
  seed: 42

model:
  type: "electra"
  name: "google/electra-base-discriminator"
  num_labels: 3
  dropout_prob: 0.1

data:
  train_path: "dataset/train"
  eval_path: "dataset/test/SemEval2017-task4-test.subtask-A.english.txt"
  max_length: 128

training:
  batch_size: 16
  learning_rate: 1e-5  # Lower LR often works better for ELECTRA
  weight_decay: 0.01
  num_epochs: 3
  warmup_proportion: 0.1
  max_grad_norm: 1.0

output:
  output_dir: "experiments/electra_base"
  save_best_only: true